spring:
  application:
    domain: inditex
    name: zara:1.0.0-SNAPSHOT
    description: zara
    version: 1.0.0-SNAPSHOT
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

api:
  endpoints:
    price:
      name: price
      mapping: /prices

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    db:
      enabled: false
    defaults:
      enabled: false
