
CREATE TABLE BRANDS (
    ID BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR(60) NOT NULL
);

CREATE TABLE PRICES (
    ID UUID PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRIORITY BIGINT NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    CONSTRAINT fk_brand FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(id)
);